version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
     - checkout
     - run:
        name: Giving permissions
        command: chmod +x mvnw
     - run:
        command: ./mvnw -Dmaven.test.skip=true package      

# VS Code Extension Version: 1.5.1