version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: chmod +x mvnw
      - run:
          name: List all files
          command: ls -la
      - run:   
          command: ./mvnw -Dmaven.test.skip=true package